apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  namespace: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
  - name: nodeapp-test
    image: jbarosin/nodeapp:dev
    ports:
      - name: nodeapp-test
        containerPort: 8000
        protocol: TCP
