apiVersion: apps/v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
  - name: nodeapp-test
    image: jbarosin/nodeapp:dev
    command: ['sh', '-c', 'echo "Hello, NodeApp from Kubernetes!" && sleep 3600']
    ports:
      - name: nodeapp-test
        containerPort: 8000
        protocol: TCP
