apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-test
  labels:
    app: nodeapp-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp-test
  template:
    metadata:
      labels:
        app: nodeapp-test
    spec:
      containers:
      - name: nodeapp-test
        image: jbarosin/nodeapp
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-test
spec:
  selector:
    app: nodeapp-test 
  ports:
    - port: 8080 
  type: LoadBalancer

